# -*- coding: utf-8 -*-
"""Training Session.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CwVNqRfmKFH3nrTz4fFN1gNahoXn-c50
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = "/content/drive/MyDrive/Training Session/laptop_data - laptop_data.csv"
df = pd.read_csv(data)

df.info()

df.shape

df.duplicated().sum()

df.isnull().sum()

df.head()

df.drop(columns=["Unnamed: 0"], inplace=True)
df

df.head()

df['Ram'] = df['Ram'].str.replace('GB', '').astype('int32')
df['Weight'] = df['Weight'].str.replace('kg', '').astype('float32')
df.head()

type(df['Ram'][0])

df.info()

"""# EDA"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.distplot(df['Price'])

df['Company'].value_counts().plot(kind='bar')

sns.barplot(x=df['Company'], y=df['Price'])

df['TypeName'].value_counts().plot(kind='bar')

sns.barplot(x=df['TypeName'], y=df['Price'])

sns.distplot(df['Inches'])

sns.barplot(x=df['Inches'], y=df['Price'])

df['ScreenResolution'].value_counts()

df['Touchscreen'] = df['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)
df.head()

df['Touchscreen'].value_counts().plot(kind='bar')

df['IPS'] = df['ScreenResolution'].apply(lambda x:1 if 'IPS' in x else 0)
df.head()

df['IPS'].value_counts().plot(kind='bar')

new = df['ScreenResolution'].str.split('x', n=1, expand=True)

df['X_res'] , df['Y_res'] = new[0], new[1]
df

